[project]
name = "polymarket-algo-core"
version = "0.2.0"
requires-python = ">=3.13"
dependencies = ["pandas>=3.0.0", "python-dotenv>=1.2.1"]

[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"
